# Generated by Django 5.1 on 2024-08-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hall',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
