# Generated by Django 5.1 on 2024-09-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_coverimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverimage',
            options={'verbose_name': 'Обложка', 'verbose_name_plural': 'Обложки'},
        ),
    ]
